### ISSUE TITLE
Turrets don't like tails

### ISSUE THREAD

**Issue by Agent-Chase-SK** [kihira/ImmersiveFloofs#1]
_This happended when I told turret to shoot pig with Random Floof Cartridge._

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-60.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-6.jar)
  ProgressionTransformer (Progression-1.10.2-0.6.9.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 3/1/17 10:59 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at uk.kihira.immersivefloofs.ImmersiveFloofs$2.getProjectile(ImmersiveFloofs.java:84)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityTurretGun.activate(TileEntityTurretGun.java:83)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityTurret.func_73660_a(TileEntityTurret.java:127)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityTurretGun.func_73660_a(TileEntityTurretGun.java:153)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at uk.kihira.immersivefloofs.ImmersiveFloofs$2.getProjectile(ImmersiveFloofs.java:84)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityTurretGun.activate(TileEntityTurretGun.java:83)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityTurret.func_73660_a(TileEntityTurret.java:127)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityTurretGun.func_73660_a(TileEntityTurretGun.java:153)

-- Block entity being ticked --
Details:
	Name: immersiveengineering:TurretGun // blusunrize.immersiveengineering.common.blocks.metal.TileEntityTurretGun
	Block type: ID #533 (tile.immersiveengineering.metalDevice1 // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice1)
	Block data value: 11 / 0xB / 0b1011
	Block location: World: (-105,70,237), Chunk: (at 7,4,13 in -7,14; contains blocks -112,0,224 to -97,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #533 (tile.immersiveengineering.metalDevice1 // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice1)
	Actual block data value: 11 / 0xB / 0b1011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: New World 5
	All players: 1 total; [EntityPlayerMP['Agent_Chase_SK'/936, l='New World 5', x=-104.67, y=72.00, z=239.86]]
	Chunk stats: ServerChunkCache: 630 Drop: 0
	Level seed: 1475500105758515400
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (-92,64,240), Chunk: (at 4,4,0 in -6,15; contains blocks -96,0,240 to -81,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1327 game time, 1327 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 120710 (now: false), thunder time: 112680 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 192077760 bytes (183 MB) / 1366294528 bytes (1303 MB) up to 2142240768 bytes (2043 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2297m -Xms256m -XX:PermSize=256m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151.jar) 
	UCHIJAAAA	Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-6} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-6.jar) 
	UCHIJAAAA	Quark{r1.0-60} [Quark] (Quark-r1.0-60.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UCHIJAAAA	DragonMounts{r46-1.10.2} [Dragon Mounts] (DragonMounts-r46-1.10.2.jar) 
	UCHIJAAAA	HardcoreQuesting{1.10.2-5.0.0beta4} [Hardcore Questing Mode] (HQM-New Heights-1.10.2-5.0.0beta4.jar) 
	UCHIJAAAA	JEI{3.14.7.415} [Just Enough Items] (jei_1.10.2-3.14.7.415.jar) 
	UCHIJAAAA	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
	UCHIJAAAA	tails{1.10.2-1.8.3} [Tails] (Tails-1.10.2-1.8.3.jar) 
	UCHIJAAAA	immersivefloofs{1.0.0} [Immersive Floofs] (ImmersiveFloofs-1.10.2-1.0.0.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	jeresources{0.5.7.87} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.87.jar) 
	UCHIJAAAA	progression{0.6.9} [Progression] (Progression-1.10.2-0.6.9.jar) 
	UCHIJAAAA	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCHIJAAAA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJAAAA	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJAAAA	RTG{4.1.1.8} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.8.jar) 
	UCHIJAAAA	sgcraft{1.13.0} [SG Craft] (SGCraft-1.13.0-mc1.10.2.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-60.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
AppEngCore (appliedenergistics2-rv4-alpha-6.jar)
  appeng.transformer.asm.ASMIntegration
ProgressionTransformer (Progression-1.10.2-0.6.9.jar)
  joshie.progression.asm.ProgressionTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv4-alpha-6 for Forge 12.18.2.2104
	AE2 Integration: IC2:OFF, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Agent_Chase_SK'/936, l='New World 5', x=-104.67, y=72.00, z=239.86]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Agent-Chase-SK** [comment]
It also happened when I shoot myself using turret with Dynamic Floof Cartridge.

**Comment by BluSunrize** [comment]
Actually, that's totally my fault. I was meaning to default bullets to be invalid for turrets. I tried to very specifically avoid this. Next IE should fix this.
